config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations'
  }
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :school_admins, controllers: {
    sessions: 'school_admins/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  scope module: :students do
    resources :schools, only: [:index] do
      member do
        get "batches", as: 'list_batches'
      end
    end
    resources :batches, only: [:show] do
      member do
        put "apply"
      end
    end
  end
  namespace :school_admins do
    resources :batches, only: [:index, :show, :create, :new, :edit, :update] do
      member do
        put "approve/:student_batch_id", to: "batches#approve", as: "approve"
        put "reject/:student_batch_id", to: "batches#reject", as: "reject"
        
        namespace :batches do
          resources :courses, param: :course_id
        end
      end
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :school
  has_many :courses
  has_many :student_batches
end

app/models/school_admin.rb
class SchoolAdmin < User
  belongs_to :school
end

app/controllers/school_admins/base_controller.rb
class SchoolAdmins::BaseController < ApplicationController
  skip_before_action :authenticate_student!, raise: false
  before_action :authenticate_school_admin!

end

app/controllers/school_admins/batches/courses_controller.rb
class SchoolAdmins::Batches::CoursesController < SchoolAdmins::BaseController
  
  before_action :set_school
  before_action :set_batch
  before_action :set_course, only: [:show, :edit, :update]
  def index
    @courses = @batch.courses.paginate(page: (params[:page]||1), per_page: PER_PAGE)
  end
  
  def show
  end
  
  def edit
  end
  
  def new
    @course = @batch.courses.new()
  end

  def create
    @course = @batch.courses.create(course_params)
    redirect_to school_admins_batches_courses_path
  end

  private
  def course_params
    params.require(:course).permit(:name)
  end

  def set_school
    @school = current_school_admin.school
  end
  
  def set_course
    @course = @batch.courses.find(params[:batch_id])
  end
  
  def set_batch
    @batch = @school&.batches.find(params[:id])
  end
end

app/controllers/school_admins/batches_controller.rb
class SchoolAdmins::BatchesController < SchoolAdmins::BaseController
  
  before_action :set_school
  before_action :set_batch, except: [:index, :new, :create]
  def index
    @batches = Batch.all.where(school_id: @school.id).paginate(page: (params[:page]||1), per_page: PER_PAGE)
  end
  
  def show
    @student_batches = @batch.student_batches.paginate(page: (params[:page]||1), per_page: PER_PAGE)
  end
  
  def approve
    mapping = @batch.student_batches.find_by(id: params[:student_batch_id])
    if mapping.approved!
      flash[:success] = "approved"
    else
      flash[:error] = "Could not approve"
    end
    redirect_to school_admins_batch_url(@batch.id)
  end

  def reject
    mapping = @batch.student_batches.find_by(id: params[:student_batch_id])
    if mapping.rejected!
      flash[:success] = "rejected"
    else
      flash[:error] = "Could not reject"
    end
    redirect_to school_admins_batch_url(@batch.id)
  end
  
  def new
    @batch = @school.batches.new()
  end
  
  def edit
  end
  
  def update
    if @batch.update(batch_params)
      flash[:success] = "saved"
    else
      flash[:error] = "Could not save"
    end
    redirect_to school_admins_batches_url
  end

  def create
    @batch = @school.batches.new(batch_params)
    if @batch.save
      flash[:success] = "saved"
    else
      flash[:error] = "Could not save"
    end
    redirect_to school_admins_batches_url
  end

  private
  def batch_params
    params.require(:batch).permit(:name)
  end

  def set_school
    @school = current_school_admin.school
  end
  
  def set_batch
    @batch = @school&.batches.find(params[:id])
  end
end

app/controllers/school_admins/homes_controller.rb
class SchoolAdmins::HomesController < SchoolAdmins::BaseController
  def index
  end
end

app/controllers/school_admins/sessions_controller.rb
# frozen_string_literal: true

class SchoolAdmins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/batches_controller.rb
class Students::BatchesController < ApplicationController
  before_action :find_batch, except: [:index]
  def index
    @batches = Batch.all
  end

  def show
    @student_batch = @batch.student_batches.find_by(student_id: current_student.id)
    @fellow_student_batches = StudentBatch.all.joins(:student).where(batch_id: @student_batch&.batch_id, status: StudentBatch.statuses[:approved]).includes(:student)
  end
  
  def apply
    mapping = @batch.student_batches.find_or_initialize_by(student_id: current_student.id)
    if mapping.save
      flash[:success] = "Raised Request to enrollment"
    else
      flash[:error] = "Could not raise Request"
    end
    redirect_to batch_url
  end
  
  private 
  
  def find_batch
    @batch = Batch.find(params[:id])
  end
end

app/views/school_admins/batches/edit.html.erb
<%= form_for @batch, url: school_admins_batch_path(@batch.id), html: { method: :put } do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/school_admins/batches/index.html.erb
<div class="">
  <%= current_school_admin.email %>
</div>
<a href="<%= new_school_admins_batch_url() %>">Create new batch</a>

<% if @school %>
  welcome to <%= @school.name %>
  <div class="">
    <% @batches.each do |batch| %>
      <li>
        <%= batch.name %>
        <a href="<%= school_admins_batch_url(batch.id) %>"> view details</a>
        <a href="<%= edit_school_admins_batch_url(batch.id) %>">edit details</a>
      </li>
    <% end %>
  </div>
  <%= will_paginate @batches %>

<% else %>
  <div class="">
    please Join a school
  </div>
<% end %>

app/views/school_admins/batches/new.html.erb
<%= form_for(@batch, url: school_admins_batches_path(@batch)) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/school_admins/batches/show.html.erb
name: <%= @batch.name %>

<br>
enrolled students: 
<% @student_batches.each do |batch| %>
<li>
  <%= batch.student.email %>: <%= batch.status %> 
  <% if batch.pending? %>
    <%= link_to 'click to approve', approve_school_admins_batch_url(id: @batch.id, student_batch_id: batch.id), class: '', data: { "turbo-method": :put } %>
    <%= link_to 'click to reject', reject_school_admins_batch_url(id: @batch.id, student_batch_id: batch.id), class: '', data: { "turbo-method": :put } %>
  <% end %>
</li>
<% end %>
<%= will_paginate @student_batches %>
<br>
view available courses: <a href="<%= school_admins_batches_courses_url(@batch.id) %>">click here</a> 