config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations'
  }
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :school_admins, controllers: {
    sessions: 'school_admins/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  scope module: :students do
    resources :schools, only: [:index] do
      member do
        get "batches", as: 'list_batches'
      end
    end
    resources :batches, only: [:show] do
      member do
        put "apply"
      end
    end
  end
  namespace :school_admins do
    resources :batches, only: [:index, :show, :create, :new, :edit, :update] do
      member do
        put "approve/:student_batch_id", to: "batches#approve", as: "approve"
        put "reject/:student_batch_id", to: "batches#reject", as: "reject"
        
        namespace :batches do
          resources :courses, param: :course_id
        end
      end
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :school
  has_many :courses
  has_many :student_batches
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
  has_many :batches
end

app/models/school_admin.rb
class SchoolAdmin < User
  belongs_to :school
end

app/models/student.rb
class Student < User
  has_many :student_batches
end

app/models/student_batch.rb
class StudentBatch < ApplicationRecord
  belongs_to :student, foreign_key: :student_id, class_name: "User"
  belongs_to :batch
  enum status: {pending: 0, approved: 1, rejected: 2}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  self.inheritance_column = :role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  PER_PAGE=5

  def after_sign_in_path_for(resource)
    respective_paths
  end
  
  def respective_paths
    if current_admin
      rails_admin_path
    elsif current_school_admin
      school_admins_batches_url
    else
      schools_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    redirect_to respective_paths
  end
end

app/controllers/students/base_contoller.rb
class Students::BaseController < ApplicationController
  before_action :authenticate_student!

end

app/controllers/students/batches_controller.rb
class Students::BatchesController < ApplicationController
  before_action :find_batch, except: [:index]
  def index
    @batches = Batch.all
  end

  def show
    @student_batch = @batch.student_batches.find_by(student_id: current_student.id)
    @fellow_student_batches = StudentBatch.all.joins(:student).where(batch_id: @student_batch&.batch_id, status: StudentBatch.statuses[:approved]).includes(:student)
  end
  
  def apply
    mapping = @batch.student_batches.find_or_initialize_by(student_id: current_student.id)
    if mapping.save
      flash[:success] = "Raised Request to enrollment"
    else
      flash[:error] = "Could not raise Request"
    end
    redirect_to batch_url
  end
  
  private 
  
  def find_batch
    @batch = Batch.find(params[:id])
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/schools_controller.rb
class Users::SchoolsController < ApplicationController
  before_action :authenticate_user!
  def index
    @schools = School.all
  end
  
  def batches
    @school = School.find(params[:id])
    @batches = @school.batches
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <span class="fs-4">SchoolManagement</span>
        </a>

        <ul class="nav nav-pills">
          <% if current_student %>
              <li class="nav-item active">
                <%= link_to 'Log Out', destroy_student_session_path, class: 'me-3 py-2 text-dark text-decoration-none', data: { "turbo-method": :delete } %>
              </li>
          <% elsif current_admin %>
              <li class="nav-item active">
                <%= link_to 'Log Out', destroy_admin_session_path, class: 'me-3 py-2 text-dark text-decoration-none', data: { "turbo-method": :delete } %>
              </li>
          <% elsif current_school_admin %>
              <li class="nav-item active">
                <%= link_to 'Log Out', destroy_school_admin_session_path, class: 'me-3 py-2 text-dark text-decoration-none', data: { "turbo-method": :delete } %>
              </li>
          <% else %>
            <li class="nav-item">
              <a href="<%= new_student_registration_path %>" class="me-3 py-2 text-dark text-decoration-none " aria-current="page">Student Sign up</a>
            </li>
            <li class="nav-item">
              <a href="<%= new_student_session_path %>" class="me-3 py-2 text-dark text-decoration-none">Log in</a>
            </li>
            <li class="nav-item">
              <a href="<%= new_admin_session_path %>" class="me-3 py-2 text-dark text-decoration-none">Admin Corner</a>
            </li>
            <li class="nav-item">
              <a href="<%= new_school_admin_session_path %>" class="me-3 py-2 text-dark text-decoration-none">School Admin Corner</a>
            </li>
          <% end %>
        </ul>
      </header>
    </div>
    <%= yield %>
  </body>
</html>